# Generated by Django 5.0.6 on 2024-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_student_stuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stuemail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stupass',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='12345', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
