# Generated by Django 5.0.6 on 2024-07-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_remove_student_stuemail_remove_student_stuname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
