# Generated by Django 5.0.6 on 2024-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='file',
            field=models.FileField(default='No file', upload_to='files'),
        ),
    ]
