# Generated by Django 5.0.6 on 2024-06-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stuid',
        ),
    ]
