# Generated by Django 5.2 on 2025-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_student_stuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stupass',
            field=models.BooleanField(default=False),
        ),
    ]
